server:
  port: 8080
spring:
  aop:
    auto: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/transactiontest?serverTimezone=UTC&useUnicode=true" +
      "&characterEncoding=utf8
  profiles:
    active: dev
