server:
  port: 8022
spring:
  #给项目来个名字
  application:
    name: rabbitmq-client
  #配置rabbitMq 服务器
  rabbitmq:
    host: 172.16.24.52
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mq_message?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&autoReconnect=true&useSSL=false&useUnicode=true
mq:
  exchange: exchange2
  queue: Q2
  routeing-key: rk_q2
