http-pool:
  max-total: 5
  default-max-per-route: 10
  connect-timeout: 5000
  connection-request-timeout: 5000
  socket-timeout: 65000
  validate-after-inactivity: 2000

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.apache.http.impl.client: debug

