server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-client
  #配置rabbitMq 服务器
  rabbitmq:
    host: 47.99.203.15
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    queue:
      orderbilling: order-billing-queue
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost
