server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-client
  #配置rabbitMq 服务器
  rabbitmq:
    host: 172.16.24.52
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
#        prefetch: 1
        retry:
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 3 #最大重试次数
          initial-interval: 5000 #重试间隔时间（单位毫秒）
          max-interval: 1200000 #重试最大时间间隔（单位毫秒）
          multiplier: 5 #应用于前一重试间隔的乘法器。

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mq_message?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&autoReconnect=true&useSSL=false&useUnicode=true
mq:
  exchange: e2
  queue: Q3
  routeing-key: rk_q2
