server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-client
  #配置rabbitMq 服务器
  rabbitmq:
    host: 172.16.24.52
    port: 5672
    username: guest
    password: guest
    virtual-host: /
mq:
  exchange: exchange2
  queue: Q2
