server:
  port: 8020
spring:
  #给项目来个名字
  application:
    name: rabbitmq-server
  #配置rabbitMq 服务器
  rabbitmq:
    host: 172.16.24.52
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: l!vWT#mL93
    url: jdbc:mysql://172.16.24.110:3306/fsp?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf8&autoReconnect=true&useSSL=false&useUnicode=true


mq:
  exchange: exchange2
  queue: Q2
