server:
  port: 8020
spring:
  #给项目来个名字
  application:
    name: rabbitmq-server
  #配置rabbitMq 服务器
  rabbitmq:
    host: 47.99.203.15
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    queue:
      orderbilling: order-billing-queue
    #虚拟host 可以不设置,使用server默认host
    publisher-confirm-type: simple
    publisher-returns: true
    publisher-confirms: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
#    virtual-host: JCcccHost
