spring:
  redis:
    host: 47.99.203.15
    database: 1
    password: credit@123
    port: 8389
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        min-idle: 1
        max-idle: 5

